- hosts: master, workers
  gather_facts: yes
  become: yes
  roles:
    - { role: roles/dependencies }

- hosts: master
  become: yes
  vars:
    master_ip: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4'].address | default(groups['master'][0]) }}"
  roles:
    - { role: roles/master }

- hosts: master
  become: yes
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars[groups['master'][0]]['join_command'] }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

- hosts: master
  become: yes
  tasks:
    - name: get master hostname
      shell: hostname
      register: master_hostname_raw

    - name: set master hostname
      set_fact:
        master_hostname: "{{ master_hostname_raw.stdout_lines[0] }}"
    
    - name: get worker hostname
      shell: kubectl get nodes -o name
      register: worker_hostname_raw

    - name: set worker hostname
      set_fact:
        worker_hostname: "{{ worker_hostname_raw.stdout_lines[1] }}"


- hosts: master
  gather_facts: true
  become: yes
  roles:
    - { role: roles/case-specific }
