
- hosts: master, workers
  gather_facts: yes
  become: yes
  roles:
    - { role: roles/dependencies }

- hosts: master
  become: yes
  roles:
    - { role: roles/master }

- hosts: master
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }}"