---
- hosts: consul-master
  become: true
  roles:
    - server
    
- hosts: consul-agents
  become: true
  roles:
    - agent
  vars:
    server_join_addr: "8.208.94.136"
    client_addr: "prometheus.sipirsipirmin.com" # tasarım hatası
    