---
- name: copy clusterconfig
  template:
    src: clusterconfig.yaml.j2
    dest: /tmp/clusterconfig.yaml
    mode: 0644
    owner: root
    group: root


- name: init cluster
  shell: kubeadm init --config /tmp/clusterconfig.yaml >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt


- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: $HOME/.kube/
    state: directory
    mode: '0755'


- name: copy kubeconfig
  shell: cp /etc/kubernetes/admin.conf $HOME/.kube/config


- name: install network plugn
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >>  network-plugin-initialized.txt
  args:
        chdir: $HOME
        creates: network-plugin-initialized.txt
  

