---
- name: consul repo add
  shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: update yum
  yum:
    update_only: yes

- name: Install consul
  yum:
    name:
      - consul
    state: present

- name: configure agent
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    mode: 0644
    owner: root
    group: root

- name: configure agent
  template:
    src: prometheus-registry.json.j2
    dest: /etc/consul.d/prometheus-registry.json
    mode: 0644
    owner: root
    group: root


- name: Enable consul
  ansible.builtin.service:
    name: consul
    enabled: yes

- name: Restart service consul
  ansible.builtin.service:
    name: consul
    state: restarted